# Generated by Django 5.0.7 on 2024-07-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="location_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
