# Generated by Django 5.0.7 on 2024-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="floor_image",
            field=models.ImageField(blank=True, null=True, upload_to="floor_images/"),
        ),
        migrations.AddField(
            model_name="location",
            name="x_coordinate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="location",
            name="y_coordinate",
            field=models.FloatField(default=0),
        ),
    ]
